title: 초보 블로그
author: kminito
email: gatsbyfor@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  안녕하세요. 취미로 프로그래밍을 시작하며 블로그가
   필요할 것 같아 만들어 본 곳입니다. 잘 부탁드립니다. 감사합니다.

# social links
# twitter_username: jekyllrb
github_username:  kminito
rss: feed
# dribbble_username: jekyll
# facebook_username:
# flickr_username: jekyll
instagram_username: cinquasi
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.html

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

disqus:
  shortname: kminito

# show_excerpts: true

url: "https://kminito.github.io/" # the base hostname & protocol for your site

google_analytics: UA-117534704-1
